// ignore_for_file: constant_identifier_names

const DEBUG_MODE = false;

const MAX_BOSS_COUNT = 100;
const BOSS_HP_PER_LEVEL_GROWTH = 0.07;
const BOSS_ATK_PER_LEVEL_GROWTH = 0.04;
const BOSS_RANDOM_STAT_VARIATION = 0.05;

const MAX_TEAM_SIZE = 5;
const MONSTER_HP_PER_LEVEL_GROWTH = 0.06;
const MONSTER_ATK_PER_LEVEL_GROWTH = 0.05;
const MONSTER_TIER_MULTIPLIER = 1.90;
const MONSTER_RANDOM_STAT_VARIATION = 0.1;